# Generated by Django 2.2.4 on 2019-08-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref',
            name='library',
        ),
        migrations.RemoveField(
            model_name='ref',
            name='pdf',
        ),
        migrations.DeleteModel(
            name='PdfFile',
        ),
        migrations.DeleteModel(
            name='Ref',
        ),
    ]
