# Generated by Django 2.2.4 on 2019-08-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_auto_20190821_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40)),
                ('pdf_file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('init_json', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_json', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=500)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.Library')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.PdfFile')),
            ],
        ),
    ]
